from datetime import datetime, timezone
from pathlib import Path
import uuid

def make_report_id():
    return "CWA-" + datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:6].upper()

def generate_delivery_report(check, filename, output_path):
    check.report_id = check.report_id or make_report_id()
    lines = [
        "CASTWISE AUDIO DOCTOR",
        "ENGINEERING DELIVERY CHECK",
        "",
        f"Report ID: {check.report_id}",
        f"Generated (UTC): {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"Profile: {check.profile}",
        f"File: {filename}",
        f"Overall Status: {check.status}",
        "",
        "CHECKS",
        "-" * 72,
    ]
    for c in check.checks:
        lines.append(f"{c.name}: {c.status} | Measured: {c.measured} | Target: {c.target}")
    if check.reasons:
        lines += ["", "NOTES / DELIVERY ISSUES", "-" * 72]
        lines.extend("- " + r for r in check.reasons)
    lines += [
        "",
        "This report is an engineering delivery check generated by Castwise Audio Doctor.",
        "It is not a regulatory, legal, or third-party certification."
    ]
    Path(output_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path
